version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: fpd_dev

    environment:
      MYSQL_USER: 'nakkim'
      MYSQL_PASSWORD: 'nakkim@test'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'

    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5001:3306
